/**
 * Shared Tool Helper
 *
 * All three summary tools follow the same pattern:
 *   1. Resolve SHARP + tool params
 *   2. Fetch patient context (live FHIR or fixture)
 *   3. Build prompt
 *   4. Generate summary via LLM or passthrough
 *   5. Return formatted result
 *
 * This helper extracts that common flow.
 */

import type { PatientContext } from "../types.js";
import { FHIRClient } from "../fhir/client.js";
import { mapToPatientContext } from "../fhir/mapper.js";
import { loadFixture, isSyntheticPatient } from "../fhir/fixtures.js";
import { resolveContext, type SharpContext } from "../utils/sharp.js";
import { SAFETY_DISCLAIMER } from "../constants.js";

/**
 * Fetch and build PatientContext from the best available source.
 */
export async function fetchPatientContext(
  sharpCtx: SharpContext | undefined,
  toolParams: { patient_id: string; fhir_server_url?: string },
  includeHistory = false
): Promise<{ context: PatientContext; warnings: string[] }> {
  const resolved = resolveContext(sharpCtx ?? {}, toolParams);
  const patientId = resolved.patientId ?? toolParams.patient_id;

  // Synthetic patient → load fixture directly
  if (isSyntheticPatient(patientId)) {
    const fixture = await loadFixture(patientId);
    if (!fixture) {
      throw new Error(`Failed to load synthetic fixture for ${patientId}`);
    }
    return {
      context: mapToPatientContext(fixture),
      warnings: fixture.warnings,
    };
  }

  // Live FHIR server → try fetch, fall back to fixture
  try {
    const client = new FHIRClient(resolved.fhirServerUrl, resolved.fhirAccessToken);
    const resources = await client.getAllResources(patientId, includeHistory);
    return {
      context: mapToPatientContext(resources),
      warnings: resources.warnings,
    };
  } catch (fetchError) {
    // Try fixture fallback
    const fixture = await loadFixture(patientId);
    if (fixture) {
      const msg = fetchError instanceof Error ? fetchError.message : String(fetchError);
      fixture.warnings.push(`Live FHIR server unreachable — using synthetic fixture. Error: ${msg}`);
      return {
        context: mapToPatientContext(fixture),
        warnings: fixture.warnings,
      };
    }
    throw fetchError;
  }
}

/**
 * Format the final tool response with metadata.
 */
export function formatToolResponse(
  summary: string,
  meta: {
    mode: "llm" | "prompt-passthrough";
    model?: string;
    warnings: string[];
    summaryType: string;
  }
): { content: Array<{ type: "text"; text: string }> } {
  const parts: string[] = [summary];

  // Add metadata footer
  const metaLines: string[] = [];
  if (meta.mode === "llm") {
    metaLines.push(`Generated by: ${meta.model ?? "LLM"}`);
  }
  if (meta.warnings.length > 0) {
    metaLines.push(`Warnings: ${meta.warnings.join("; ")}`);
  }

  if (metaLines.length > 0) {
    parts.push("\n\n---");
    parts.push(`_${metaLines.join(" | ")}_`);
  }

  // Ensure safety disclaimer is present
  if (!summary.includes(SAFETY_DISCLAIMER)) {
    parts.push(`\n\n${SAFETY_DISCLAIMER}`);
  }

  return {
    content: [{ type: "text" as const, text: parts.join("\n") }],
  };
}
